# Python Math Notes

## Linear Algebra Notes

### Matrices

#### Identity Matrix

In [1]:
import numpy as np

I = np.identity(6) # size of matrix

print("6x6 identity matrix: ")
print(I)

6x6 identity matrix: 
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


#### Inverse Matrix

In [10]:
import numpy as np

A = np.array([[1,2,3],
              [2,5,7],
              [3,8,9]])
A_inv = np.linalg.inv(A)

print("A inverse: ")
print(A_inv)

A inverse: 
[[ 5.5 -3.   0.5]
 [-1.5 -0.   0.5]
 [-0.5  1.  -0.5]]


#### Matrix Raised to Power
The code below raises the matrix $P$ to the 3rd power, or $P^{3}$.

In [ ]:
import numpy as np

P = np.identity(3)                  # Set P to the identity matrix
P_3 = np.linalg.matrix_power(P,3)   # Cube P

#### Permutation Matrix
The code below generates 4x4 permutation matrices.

In [2]:
import numpy as np

I = np.identity(4)                  # Create 4x4 identity matrix
P = np.random.permutation(I)        # Permutate the matrix