# Math Reference Notes

## Linear Algebra Notes

### Matrices

#### Identity Matrix

In [2]:
import numpy as np

I = np.identity(6) # size of matrix

print("3x3 identity matrix: ")
print(I)

3x3 identity matrix: 
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


#### Inverse Matrix

In [10]:
import numpy as np

A = np.array([[1,2,3],
              [2,5,7],
              [3,8,9]])
A_inv = np.linalg.inv(A)

print("A inverse: ")
print(A_inv)

A inverse: 
[[ 5.5 -3.   0.5]
 [-1.5 -0.   0.5]
 [-0.5  1.  -0.5]]
