### Linear Algebra Reference Notes

#### Matrix Multiplication

##### Matrix Times Column

* For matrix multiplication $AB$, where $A$ and $B$ are matrices, if $A$ has $n$ columns, $B$ must have $n$ rows.
* If $A$ is $m \times n$ and $B$ is $n \times p$ then
$$
(m \times n )(n \times p) = (m \times p)
$$



$$

\begin{bmatrix}
\text{m rows}    \\
\text{n columns} \\
\end{bmatrix}

\begin{bmatrix}
\text{n rows}    \\
\text{p columns} \\
\end{bmatrix}

=

\begin{bmatrix}
\text{m rows}    \\
\text{p columns} \\
\end{bmatrix}

$$

* Row times column. Also called _inner product_ or _dot product_. Result is scalar or 1 $\times$ 1.

$$

\begin{bmatrix}
0 & 1 & 2 \\
\end{bmatrix}

\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}

=

8
$$

* Column times row. Also called _outer product_. If column is $n \times 1$ and row is $1 \times n$, then result is $n \times n$.

$$

\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}

\begin{bmatrix}
0 & 1 & 2 \\
\end{bmatrix}

=

\begin{bmatrix}
0 & 1 & 2 \\
0 & 2 & 4 \\
0 & 3 & 6 \\
\end{bmatrix}

$$

* Column picture - Multiplying from right to left. Each column of $B$ combines all columns of $A$ and stores into corresponding column of $AB$.
* Row picture - Multiplying from left to right. Each row of $A$ combines all rows of $B$ and stores into corresponding row of $AB$.

In [5]:
import numpy as np

u = np.array([[0, 1, 2]])
v = np.array([[1],[2],[3]])
w = np.dot(u,v)
z = np.dot(v,u)

print("w = \n")
print(w)

print("\nv = \n")
print(z)

w = 

[[8]]

v = 

[[0 1 2]
 [0 2 4]
 [0 3 6]]


##### Matrix multiplication by combining rows
![title](./images/lect02_img01_matrix_performing_row_ops.png)

##### Matrix multiplication by combining columns
![title](./images/lect02_img02_matrix_performing_col_ops.png)

#### Pascal's Triangle
* Each entry is the sum of the one above it plus the one to the upper left. For example, the 3 in (4,2) is the sum of 2 in (3,2) and 1 in (3,1).

$$

\begin{bmatrix}
1 & 0 & 0 & 0 \\
1 & 1 & 0 & 0 \\
1 & 2 & 1 & 0 \\
1 & 3 & 3 & 1 \\
\end{bmatrix}

$$