### Linear Algebra Reference Notes

#### Matrix Multiplication

##### Matrix Times Column

* For matrix multiplication $AB$, where $A$ and $B$ are matrices, if $A$ has $n$ columns, $B$ must have $n$ rows.
* If $A$ is $m \times n$ and $B$ is $n \times p$ then
$$
(m \times n )(n \times p) = (m \times p)
$$



$$

\begin{bmatrix}
\text{m rows}    \\
\text{n columns} \\
\end{bmatrix}

\begin{bmatrix}
\text{n rows}    \\
\text{p columns} \\
\end{bmatrix}

=

\begin{bmatrix}
\text{m rows}    \\
\text{p columns} \\
\end{bmatrix}

$$

* Row times column. Also called _inner product_ or _dot product_. Result is scalar or 1 $\times$ 1.

$$

\begin{bmatrix}
0 & 1 & 2 \\
\end{bmatrix}

\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}

=

8
$$

* Column times row. Also called _outer product_. If column is $n \times 1$ and row is $1 \times n$, then result is $n \times n$.

$$

\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}

\begin{bmatrix}
0 & 1 & 2 \\
\end{bmatrix}

=

\begin{bmatrix}
0 & 1 & 2 \\
0 & 2 & 4 \\
0 & 3 & 6 \\
\end{bmatrix}

$$

* Column picture - Multiplying from right to left. Each column of $B$ combines all columns of $A$ and stores into corresponding column of $AB$.
* Row picture - Multiplying from left to right. Each row of $A$ combines all rows of $B$ and stores into corresponding row of $AB$.

In [5]:
import numpy as np

u = np.array([[0, 1, 2]])
v = np.array([[1],[2],[3]])
w = np.dot(u,v)
z = np.dot(v,u)

print("w = \n")
print(w)

print("\nv = \n")
print(z)

w = 

[[8]]

v = 

[[0 1 2]
 [0 2 4]
 [0 3 6]]


#### Matrix Multiplication - Left vs Right, Rows vs Columns

##### Multiplying matrices left to right adds rows

Below, the matrix $E$ adds rows 1 and 4 of matrix $A$ and places the result in row 4.

This matrix can also be designated as $E_{41}$. More info below.
* It adds rows 4 and 1 and places result in row 4.
* It shows what element of the identity matrix has been modified to perform the operation: element (4,1) or row 4 column 1 of the identity matrix is changed so that rows 4 and 1 are added and placed into row 4. If it was $E_{32}$, then element (3,2) of the identity matrix would be changed and the operation would multiply row 2 by some value, add to row 3, and store the result in row 3.
* Another way to read $E_{xy}$ is scale y by some value, add it to row x, and store the result in row x. So $E_{13}$ would be scale row 3, add it to row 1, and store the result in row 1.
* These are also called _elimination matrices_ when used in the elimination process to determine the pivots of a matrix, or in other words, make a matrix upper triangular.

Feel free to play with the code and try different cases.

In [ ]:
import numpy as np

# Elimination matrix E_41
E = np.array([[ 1,  0,  0,  0],     # R1 = 1*R1 + 0*R2 + 0*R3 + 0*R4
              [ 0,  1,  0,  0],     # R2 = 0*R1 + 1*R2 + 0*R3 + 0*R4
              [ 0,  0,  1,  0],     # R3 = 0*R1 + 0*R2 + 1*R3 + 0*R4
              [ 1,  0,  0,  1]])    # R4 = 1*R1 + 0*R2 + 0*R3 + 1*R4

# Test matrix
A = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12],
              [13, 14, 15, 16]])

EA = np.matmul(A,E)

print("EA = \n")
print(EA)

EA = 

[[ 5  2  3  4]
 [13  6  7  8]
 [21 10 11 12]
 [29 14 15 16]]


##### Multiplying matrices right to left adds columns

Below, the matrix $E$ adds columns 1 and 4 of matrix $A$ and places the result in column 1.

Note that this is the same code as above, except the order of the matrix multiplication has changed.

In [3]:
import numpy as np

# Elimination matrix
E = np.array([[ 1,  0,  0,  0],     
              [ 0,  1,  0,  0],
              [ 0,  0,  1,  0],
              [ 1,  0,  0,  1]])

#     C1        C2          C3          C4
# = 1*C1    = 0*C1      = 0*C1      = 0*C1
# + 0*C2    + 1*C2      + 0*C2      + 0*C2
# + 0*C3    + 0*C3      + 1*C3      + 0*C3
# + 1*C4    + 0*C4      + 0*C4      + 0*C4

# Test matrix
A = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12],
              [13, 14, 15, 16]])

AE = np.matmul(A,E) # Multiplying right to left, AE

print("AE = \n")
print(AE)

AE = 

[[ 5  2  3  4]
 [13  6  7  8]
 [21 10 11 12]
 [29 14 15 16]]


#### Pascal's Triangle
* Each entry is the sum of the one above it plus the one to the upper left. For example, the 3 in (4,2) is the sum of 2 in (3,2) and 1 in (3,1).

$$

\begin{bmatrix}
1 & 0 & 0 & 0 \\
1 & 1 & 0 & 0 \\
1 & 2 & 1 & 0 \\
1 & 3 & 3 & 1 \\
\end{bmatrix}

$$