## Assignment 1

### Section 1.2

#### Problem 23

Just use the geometric definition of cos and sin. In general, if $cosx = \frac{adjacent}{hypotenuse}$, then here, $cos\beta = \frac{w_{1}}{||w||}$. Similarly, since $sinx = \frac{opposite}{hypotenuse}$, then here, $sin\beta = \frac{w_{2}}{||w||}$.

#### Problem 28

Yes. If $x\cdot y < 0$, the angle between them is $\theta > 90°$. The problem is asking if there can be three vectors where the angle between each of them is > 90°. This is definitely possible: 3 vectors joined at their tails with more than 90 degrees between them can be drawn. An example would be slicing a circle 3 into three equal pieces, with the lines between the slices being the vectors. The angle between each vector is 360°/3 = 120°, which is greater than 90°.

### Section 1.3

#### Problem 4

Will first determine if matrix is singular by seeing if its determinant is 0.

In [1]:
import numpy as np

A = np.array([[1,4,7],
              [2,5,8],
              [3,6,9]])

det = np.linalg.det(A)

print("Matrix A: ")
print(A)

if det == 0:
    print("A is singular since det(A) == " + str(det))
else:
    print("A is invertible since det(A) == " + str(det) + " and is != 0")

Matrix A: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
A is singular since det(A) == 0.0


I couldn't figure out the combinations off the top of my head that would show that some of the vectors are linearly independent. Looked at solutions for answer.

#### Problem 13

Will probably skip most challenge problems.

### Section 2.1

#### Problem 1

Row 1, or $1x + 0y + 0z = 2$, is the vertical plane parallel to the $yz$ plane intersecting the x-axis at x = 2.

#### Problem 29

In [2]:
import numpy as np

A = np.array([[0.8,0.3],
              [0.2,0.7]])
u1 = np.array([0.6,0.4])

Au1 = np.dot(A,u1)

print("Matrix A = ")
print(A)
print("\n")

print("u1 = ")
print(u1)
print("\n")

print("Au1 = ")
print(Au1)

Matrix A = 
[[0.8 0.3]
 [0.2 0.7]]


u1 = 
[0.6 0.4]


Au1 = 
[0.6 0.4]


Used code above to keep multiplying A by consecutive u's and generate more u's to find a pattern. After generating 5 u's, this is what I found:

* The components of every u add to 1.
* To find the next u, 
    * The first element in u: take the difference between current and previous. Divide by 2. Subtract from current.
    * The second element in u: take the difference between current and previous. Divide by 2. Add to current.

#### Problem 30

For Problem 29, compute up to 7 iterations of u, plot them, and see if the iterations appear to convert to some value.

In [2]:
import numpy as np

A = np.array([[0.8, 0.3],
              [0.2, 0.7]])

u = np.array([1,0])
x = u

k = np.arange(8) # Index array 1-7 for plotting

for m in k:
    u = np.dot(A,u)
    x = np.append(x, u)
    print(u)


[0.8 0.2]
[0.7 0.3]
[0.65 0.35]
[0.625 0.375]
[0.6125 0.3875]
[0.60625 0.39375]
[0.603125 0.396875]
[0.6015625 0.3984375]


Need to add code to plot, but it can be seen above that the numbers appear to converge to 0.6 in column 1 and 0.4 in column 2. If we use u = [0.6, 0.4] and multiply against A, we get u back, as suggested in the problem. See below.

In [ ]:
A = np.array([[0.8, 0.3],
              [0.2, 0.7]])

u = np.array([0.6, 0.4])

s = np.dot(A,u)

print(s)

[0.6 0.4]


### Section 2.2

#### Problem 20

My original answer was "multiple". However, the solution manual -- and proper answer -- is "linear combination", because the rows can also be added together.

I just multiplied row 2 by -1: 

$-x+2y+z = -1$

#### Problem 32

a) I got this wrong. Answer is 0. \
b) I got this wrong. Answer is 0. \
c) Matrix of all 1's. \
d) Matrix of all 1's: \
    i) Row picture: a diagonal plane. Since all the rows are the same, all the diagonal planes are the same, or in the same place. \
    ii) Col picture: a diagonal vector. Since all the columns are the same, all the column vectors are the same diagonal vector, or in the same position.


### Section 2.3

#### Problem 22

Problem is pretty straight forward, though I initially messed up my answers for b and c. Just need to keep in mind that $E_{21}$ adds negative row 1 to row 2 for $A$. See solutions for answers.

#### Problem 29

##### Part A

Find the triangular matrix $E$ that reduces "Pascal's matrix" to a smaller Pascal. See the matrix equation shown in the book.

The row operations needed to get the RHS of the equation are

R2 = R2 - R1
R3 = R3 - R2
R4 = R4 - R3

Look at the first row operation. For operations stored in R2, you modify R2 of the identity matrix. So R2 = R2 - R1 translates to R2 = -1 1 0 0.

Do similar operations for the next 2 row operations:
R3 = R3 - R2 --> R3 = 0 -1  1 0
R4 = R4 - R3 --> R4 = 0  0 -1 1

Do all these matrix modifications to the same identity matrix. The result is

$$
\begin{bmatrix}
 1 &  0 &  0 & 0 \\
-1 &  1 &  0 & 0 \\
 0 & -1 &  1 & 0 \\
 0 &  0 & -1 & 1 \\
\end{bmatrix}
$$

##### Part B
Find the matrix that reduces Pascal all the way to $I$.

We'll start with the result above since that reduced the original Pascal somewhat.

The following row operations will be done on the matrix above to get $I$.

Row operation       Elimination matrix \
R3 = R3 - R2        ($E_{32}$) \
R4 = R4 - R2        ($E_{42}$) \
R4 = R4 - 2*R2      ($E_{43}$)

In part A, the row operations did not depend on each other. Here they do, e.g. the last row operation uses the result from the previous row operation. Thus, we need to take the corresponding matrices (noted after each row operation in parentheses) associated with each row operation and multiply them in order.

So we want

$$
E_{43}E_{42}E_{32}
$$

However, this isn't the full matrix needed to reduce the original Pascal to $I$. We actually need the matrix result from part A, since that's where we started. We'll call that A.

$$
E_{43}E_{42}E_{32}A
$$

You can either multiply this out, or the shortcut way is to just do the row operations on A, and work through the equation from right to left.

The result is the same as the solution's answer. 



### Section 2.4

#### Problem 32

If $A$ times an $x$ column vector produces an $Ax_{n}$ column vector, then putting all the $x$ column vectors into a matrix $X$ and multiplying $A$ against it just aggregates the $Ax_{n}$ column vectors into a matrix.

$$
AX = 

\begin{bmatrix}
Ax_{1} & Ax_{1} & Ax_{1} \\
\end{bmatrix}

=

\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}

$$

What the solutions PDF revealed to me is that this is the identity matrix (facepalm).

#### Problem 36

##### Part A

$m = 2, n = 4, p = 7, q = 10$ is given. Substituting these values in the two matrix equations results in,

$$
(AB)C = mnp + mpq = mp(n+q) = 2\cdot7(4+10) = 196
$$

$$
A(BC) = mnq + npq = nq(m+p) = 4\cdot10(2+7) = 360
$$

I prefer the first equation since it has fewer multiplications than the second equation.

##### Part B

Since $u, v, and w$ have the same length $N$, $(u^{T}v)w$ has the form

$$
\begin{bmatrix}
a & b & c & ... & N \\
\end{bmatrix}

\begin{bmatrix}
a \\
b \\
c \\
... \\
N \\
\end{bmatrix}

\begin{bmatrix}
a & b & c & ... & N \\
\end{bmatrix}

$$

where the left vectors must be multiplied first, with the result being multiplied against the last right-most vector.

Multiplying the first two vectors requires $N$ multiplies. The results of this multiplication is a scalar value. This scalar value times the last vector requires $N$ multiplies. Thus, the total number of multiplies for this $(u^{T}v)w$ requires $N + N = 2N$ multiplies.

$u^{T}(vw^{T})$ is similar, except the right two vectors are multiplied first, and its result multiplied by the vector on the left. Multiplying the two right vectors requires $N^{2}$ multiplies and the result is an $N$ x $N$ matrix. The resulting matrix is then multiplied by the vector on the left. This multiplication requires $N^{2}$ multiplies as well. Thus the total matrix equation $(u^{T}v)w$ requires $2N^{2}$ multiplies.

I prefer $(u^{T}v)w$ since it requires considerably fewer multiplies.

##### Part C

Since 

$$
(AB)C = mnp + mpq
$$ 

and 

$$
A(BC) = mnq + npq
$$

dividing both equations by $mnpq$ results in 

$$
\frac{(AB)C}{mnpq} = \frac{mnp + mpq}{mnpq} = \frac{1}{q} + \frac{1}{n}
$$

$$
\frac{A(BC)}{mnpq} = \frac{mnq + npq}{mnpq} = \frac{1}{p} + \frac{1}{m}
$$

Substituting in the values for $m, n, p,$ and $q$ on the right hand side

$$
\frac{1}{q} + \frac{1}{n} = 1/10 + 1/4 = 7/20
$$

$$
\frac{1}{p} + \frac{1}{m} = 1/7 + 1/2 = 9/14
$$

7/20 < 9/14 so $(AB)C < A(BC)$

### Section 2.5
#### Problem 5

The problem wants us to find an upper triangular matrix that when multiplied by itself results in the identity matrix, i.e. $U^{2} = I$.

A generic upper triangular matrix can be constructed with variable entries and used in $U^{2} = I$ to determine the matrix entries.

$$

\begin{bmatrix}
a & b & c \\
0 & d & e \\
0 & 0 & f \\
\end{bmatrix}

\begin{bmatrix}
a & b & c \\
0 & d & e \\
0 & 0 & f \\
\end{bmatrix}

=

\begin{bmatrix}
a^{2} & ab+bd & ac+be+cf \\
0 & d^{2} & de+ef \\
0 & 0 & f^{2} \\
\end{bmatrix}

$$

Setting the right hand side matrix to $I$

$$

\begin{bmatrix}
a^{2} & ab+bd & ac+be+cf \\
0 & d^{2} & de+ef \\
0 & 0 & f^{2} \\
\end{bmatrix}

=

\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}

$$

leads to equations

$$

a^{2} = 1,\\
d^{2} = 1,\\
f^{2} = 1,\\
ab+bd = 0,\\
de+ef = 0,\\
ac+be+cf = 0\\

$$

There are probably multiple combinations of $a, b, c, d, e,$ and $f$ to satisfy these equations. The values I chose were $a=1, b=2, c=-2, d=-1, e=2$. The resulting matrix is

$$
U

=

\begin{bmatrix}
1 &  2 & -2 \\
0 & -1 &  2 \\
0 &  0 &  1 \\
\end{bmatrix}

$$

The Python code below shows $U^{2} = I$ and $U= U ^{-1}$.

In [1]:
import numpy as np

U = np.array([[1, 2, -2],
              [0, -1, 2],
              [0, 0, 1]])

U_squared = np.matmul(U,U)

W = np.linalg.inv(U)

print("U = ")
print(U)
print("\n")

print("U squared = ")
print(U_squared)
print("\n")

print("U inverse = ")
print(W)


U = 
[[ 1  2 -2]
 [ 0 -1  2]
 [ 0  0  1]]


U squared = 
[[1 0 0]
 [0 1 0]
 [0 0 1]]


U inverse = 
[[ 1.  2. -2.]
 [-0. -1.  2.]
 [ 0.  0.  1.]]


#### Problem 7

##### Part A
Suppose a matrix $A$ such that its third row is the sum of the first two rows.

Show that there exists no $x$ to produce the right hand side (1, 0, 0).

The following is our answer.

Given that row 3 of $A$ is row 1 + row 2, the matrix equation can be constructed as

$$

\begin{bmatrix}
A_{1} \\
A_{2} \\
A_{3} \\
\end{bmatrix}

\begin{bmatrix}
x \\
\end{bmatrix}

=

\begin{bmatrix}
1 \\
0 \\
0 \\
\end{bmatrix}

$$

which means

$$
A_{1}x = 1, A_{2}x = 0, A_{3}x = 0
$$

Since the third row is the sum of the first and second row,

$$
A_{3}x = (A_{1}+A_{2})x = A_{1}x + A_{2}x = 0
$$

Substituting $A_{1}x = 1$ and $A_{2}x = 0$ from before leads to

$$
1 + 0 = 0
$$

which is a contradiction. Thus, there is no $x$ to satisfy $Ax = b$, where $b = (1, 0, 0)$.

##### Part B

The matrix equation we have is

$$

\begin{bmatrix}
A_{1} \\
A_{2} \\
A_{3} \\
\end{bmatrix}

\begin{bmatrix}
x \\
\end{bmatrix}

=

\begin{bmatrix}
b_{1} \\
b_{2} \\
b_{3} \\
\end{bmatrix}

$$

where

$$
A_{1}x = b_{1}, \\
A_{2}x = b_{2}, \\
A_{3}x = b_{3}, \\
$$

Since the third row is the sum of the first and second rows,

$$
A_{3}x = (A_{1} + A_{2})x = A_{1}x + A_{2}x = b_{3}
$$

Substituting in $A_{1}x = b_{1}$ and $A_{2}x = b_{2}$ from before leads to

$$
b_{1} + b_{2} = b_{3}
$$

So

$$
b

=

\begin{bmatrix}
b_{1} \\
b_{2} \\
b_{3} \\
\end{bmatrix}

=

\begin{bmatrix}
b_{1} \\
b_{2} \\
b_{1} + b_{2} \\
\end{bmatrix}

$$

is the right side $b$ where solutions for $Ax = b$ are possible.

##### Part C

Row 3 during the elimination process will turn into all zeros.