## Assignment 1

### Section 1.2

#### Problem 23

Just use the geometric definition of cos and sin. In general, if $cosx = \frac{adjacent}{hypotenuse}$, then here, $cos\beta = \frac{w_{1}}{||w||}$. Similarly, since $sinx = \frac{opposite}{hypotenuse}$, then here, $sin\beta = \frac{w_{2}}{||w||}$.

#### Problem 28

Yes. If $x\cdot y < 0$, the angle between them is $\theta > 90°$. The problem is asking if there can be three vectors where the angle between each of them is > 90°. This is definitely possible: 3 vectors joined at their tails with more than 90 degrees between them can be drawn. An example would be slicing a circle 3 into three equal pieces, with the lines between the slices being the vectors. The angle between each vector is 360°/3 = 120°, which is greater than 90°.

### Section 1.3

#### Problem 4

Will first determine if matrix is singular by seeing if its determinant is 0.

In [7]:
import numpy as np

A = np.array([[1,4,7],
              [2,5,8],
              [3,6,9]])

det = np.linalg.det(A)

print("Matrix A: ")
print(A)

if det == 0:
    print("A is singular since det(A) == " + str(det))
else:
    print("A is invertible since det(A) == " + str(det) + " and is != 0")

Matrix A: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
A is singular since det(A) == 0.0


I couldn't figure out the combinations off the top of my head that would show that some of the vectors are linearly independent. Looked at solutions for answer.

#### Problem 13

Will probably skip most challenge problems.

### Section 2.1

#### Problem 1

Row 1, or $1x + 0y + 0z = 2$, is the vertical plane parallel to the $yz$ plane intersecting the x-axis at x = 2.

#### Problem 29

In [20]:
import numpy as np

A = np.array([[0.8,0.3],
              [0.2,0.7]])
u1 = np.array([0.6,0.4])

Au1 = np.dot(A,u1)

print("Matrix A = ")
print(A)
print("\n")

print("u1 = ")
print(u1)
print("\n")

print("Au1 = ")
print(Au1)

Matrix A = 
[[0.8 0.3]
 [0.2 0.7]]


u1 = 
[0.6 0.4]


Au1 = 
[0.6 0.4]


Used code above to keep multiplying A by consecutive u's and generate more u's to find a pattern. After generating 5 u's, this is what I found:

* The components of every u add to 1.
* To find the next u, 
    * The first element in u: take the difference between current and previous. Divide by 2. Subtract from current.
    * The second element in u: take the difference between current and previous. Divide by 2. Add to current.

#### Problem 30

For Problem 29, compute up to 7 iterations of u, plot them, and see if the iterations appear to convert to some value.

In [11]:
import numpy as np

A = np.array([[0.8, 0.3],
              [0.2, 0.7]])

u = np.array([1,0])

k = np.arange(8) # Index array 1-7 for plotting

for m in k:
    u = np.dot(A,u)
    x = np.append(x, u)
    print(u)


[0.8 0.2]
[0.7 0.3]
[0.65 0.35]
[0.625 0.375]
[0.6125 0.3875]
[0.60625 0.39375]
[0.603125 0.396875]
[0.6015625 0.3984375]


Need to add code to plot, but it can be seen above that the numbers appear to converge to 0.6 in column 1 and 0.4 in column 2. If we use u = [0.6, 0.4] and multiply against A, we get u back, as suggested in the problem. See below.

In [12]:
A = np.array([[0.8, 0.3],
              [0.2, 0.7]])

u = np.array([0.6, 0.4])

s = np.dot(A,u)

print(s)

[0.6 0.4]


### Section 2.2

#### Problem 20

My original answer was "multiple". However, the solution manual -- and proper answer -- is "linear combination", because the rows can also be added together.

I just multiplied row 2 by -1: 

$-x+2y+z = -1$

#### Problem 32

a) I got this wrong. Answer is 0. \
b) I got this wrong. Answer is 0. \
c) Matrix of all 1's. \
d) Matrix of all 1's: \
    i) Row picture: a diagonal plane. Since all the rows are the same, all the diagonal planes are the same, or in the same place. \
    ii) Col picture: a diagonal vector. Since all the columns are the same, all the column vectors are the same diagonal vector, or in the same position.
