## Assignment 2

### Section 2.5

#### Problem 24
This problem is relatively straight forward. The left matrix

$$

\begin{bmatrix}
1 & a & b \\
0 & 1 & c \\
0 & 0 & 1 \\
\end{bmatrix}

$$

is $U$. As the problem states, take $U$, augment the identity matrix onto its right

$$

\begin{bmatrix}
1 & a & b & 1 & 0 & 0 \\
0 & 1 & c & 0 & 1 & 0 \\
0 & 0 & 1 & 0 & 0 & 1 \\
\end{bmatrix}

$$

and perform Gauss-Jordan elimination.

Side note: The Gauss part of elimination has been done (forward elimination) so the Jordan part of elimination is what remains.

For Gauss-Jordan elimination here, we need to continue elimination on the left side until it is the identity matrix. The right side will then be $U^{-1}$. 

This leads to

$$
U^{-1} = 

\begin{bmatrix}
1 & -a & ac-b \\
0 &  1 &   -c \\
0 &  0 &    1 \\
\end{bmatrix}

$$

#### Problem 40
Pretty straightforward. Just did Gauss-Jordan elimination to find the inverse as instructed by the problem. The solutions has this way, as well as a more interesting way.



### Section 2.6
#### Problem 13

The problem asks to find $L$ and $U$ for the matrix $A$ below

$$

A = 

\begin{bmatrix}
a & a & a & a \\
a & b & b & b \\
a & b & c & c \\
a & b & c & d \\
\end{bmatrix}

$$

One method is to do row operations until $A$ is upper triangular.

Clear below the first pivot with the following operations:
* Row 2 = R2 - R1. This is the elimination matrix $E_{21}$.
* Row 3 = R3 - R1. This is the elimination matrix $E_{31}$.
* Row 4 = R4 - R1. This is the elimination matrix $E_{41}$.

This leaves

$$

\begin{bmatrix}
a & a   & a   &   a \\
0 & b-a & b-a & b-a \\
0 & b-a & c-a & c-a \\
0 & b-a & c-a & d-a \\
\end{bmatrix}

$$

Next, clear below the second pivot with the following operations:
* Row 3 = R3 - R2. This is the elimination matrix $E_{32}$.
* Row 4 = R4 - R2. This is the elimination matrix $E_{42}$.

This leaves

$$

\begin{bmatrix}
a & a   & a   &   a \\
0 & b-a & b-a & b-a \\
0 & 0   & c-b & c-b \\
0 & 0   & c-b & d-b \\
\end{bmatrix}

$$

Lastly, clear below the third pivot with the following operation:
* Row 4 = R4 - R3. This is the elimination matrix $E_{43}$.

This leaves

$$
U = 

\begin{bmatrix}
a & a   & a   &   a \\
0 & b-a & b-a & b-a \\
0 & 0   & c-b & c-b \\
0 & 0   & 0   & d-c \\
\end{bmatrix}

$$

This is the upper triangular $U$ we want.

Now to find $L$.

The entire row elimination done above is equivalent to 

$$

E_{43}E_{42}E_{32}E_{41}E_{32}E_{31}A = U

$$

This can be used to find $L$.

$$
E_{43}E_{42}E_{32}E_{41}E_{32}E_{31}A = U
$$

$$
A = E_{31}^{-1}E_{32}^{-1}E_{41}^{-1}E_{32}^{-1}E_{42}^{-1}E_{43}^{-1}U
$$

$$
A = LU
$$

So

$$
L = E_{31}^{-1}E_{32}^{-1}E_{41}^{-1}E_{32}^{-1}E_{42}^{-1}E_{43}^{-1}
$$

The inverse elimination matrices are equal to their corresponding elimination matrix, except the modified entry is negated. For example, if 

$$
E_{42} = 

\begin{bmatrix}
1 &  0 & 0 & 0 \\
0 &  1 & 0 & 0 \\
0 &  0 & 1 & 0 \\
0 & -1 & 0 & 1 \\

\end{bmatrix}
$$

then

$$
E_{42}^{-1} = 

\begin{bmatrix}
1 &  0 & 0 & 0 \\
0 &  1 & 0 & 0 \\
0 &  0 & 1 & 0 \\
0 &  1 & 0 & 1 \\
\end{bmatrix}
$$

Multiply the inverse matrices together to find $L$.

Multiplying all six matrices together is not so bad if done in pairs and using the row operation trick. For example

$$
(E_{31}^{-1}E_{32}^{-1})(E_{41}^{-1}E_{32}^{-1})(E_{42}^{-1}E_{43}^{-1})
$$

can be done to reduce down to three matrices. For example, for the first pair $E_{31}^{-1}E_{32}^{-1}$, add rows 1 and 3 of $E_{32}^{-1}$ and place the result into its row 3.

The result of multiplying all six matrices together is

$$
L = 

\begin{bmatrix}
1 &  0 & 0 & 0 \\
1 &  1 & 0 & 0 \\
1 &  1 & 1 & 0 \\
1 &  1 & 1 & 1 \\
\end{bmatrix}
$$

Looking at the pivots of $U$, if they are to be non-zero, then $a \neq 0, b \neq a, c \neq b,$ and $ d \neq c$.

#### Problem 18

Given $A = LDU$ and $A = L_{1}D_{1}U_{1}$, with all factors invertible, derive 

$$
L_{1}^{-1}LD = D_{1}U_{1}U^{-1}
$$

Since $A$ equals both right hand sides, set them equal to each other.

$$
LDU = L_{1}D_{1}U_{1}
$$

Move $L_{1}$ from right to left side by multiplying on the left of both sides by $L_{1}^{-1}$.

$$
L_{1}^{-1}LDU = L_{1}^{-1}L_{1}D_{1}U_{1}
$$
$$
L_{1}^{-1}LDU = D_{1}U_{1}
$$

Move $U$ from left to right side by multiplying on the right of both sides by $U^{-1}$.

$$
L_{1}^{-1}LDUU^{-1} = D_{1}U_{1}U^{-1}
$$
$$
L_{1}^{-1}LD = D_{1}U_{1}U^{-1}
$$

The question also asks if the two sides of the equation are triangular or diagonal. I'm not sure if my answer is correct, but since the problem also states that $L=L_{1}, D=D_{1},$ and $U=U_{1}$, then

$$
L^{-1}LD = DUU^{-1}
$$

which reduces to

$$
D = D
$$

which is diagonal. Diagonal is the right answer, but I don't know if this solution is correct.


#### Problem 25

Given the following Toeplitz matrix

$$
K =
\begin{bmatrix}
 2 & -1 &  0 &  0 &  0 &  0 \\
-1 &  2 & -1 &  0 &  0 &  0 \\
 0 & -1 &  2 & -1 &  0 &  0 \\
 0 &  0 & -1 &  2 & -1 &  0 \\
 0 &  0 &  0 & -1 &  2 & -1 \\
 0 &  0 &  0 &  0 & -1 &  2 \\
\end{bmatrix}

$$

we must do two things: decompose $K$ into $L$ and $U$ such that $K = LU$, and create a formula for the $i, j$ entry of $L^{-1}$.

Given $K$, we will do forward elimination with row operations until $K$ is upper triangular. Each row operation is recorded by an elimination matrix.

$$ R2 += \frac{1}{2}R1, E_{21} $$
$$ R3 += \frac{2}{3}R2, E_{32} $$
$$ R4 += \frac{3}{4}R3, E_{43} $$
$$ R5 += \frac{4}{5}R4, E_{54} $$
$$ R6 += \frac{5}{6}R5, E_{65} $$

The first line means $R2 = R2 + \frac{1}{2}\cdot R1$ and the elimination matrix for this row operation is $E_{21}$.

Performing these row operations on $K$ gives $U$

$$
U =
\begin{bmatrix}
 2 &          -1 &           0 &           0 &           0 &           0 \\
 0 & \frac{3}{2} &          -1 &           0 &           0 &           0 \\
 0 &           0 & \frac{4}{3} &          -1 &           0 &           0 \\
 0 &           0 &           0 & \frac{5}{4} &          -1 &           0 \\
 0 &           0 &           0 &           0 & \frac{6}{5} &          -1 \\
 0 &           0 &           0 &           0 &           0 & \frac{7}{6} \\
\end{bmatrix}
$$

Performing these row operations on $K$ to produce $U$ is equivalent to

$$
E_{65}E_{54}E_{43}E_{32}E_{21}K = U
$$
$$
K = E_{21}^{-1}E_{32}^{-1}E_{43}^{-1}E_{54}^{-1}E_{65}^{-1}U
$$
$$
K = LU
$$

So

$$
L = E_{21}^{-1}E_{32}^{-1}E_{43}^{-1}E_{54}^{-1}E_{65}
$$

So we will perform the "inverse" of the row operations on an identity matrix to find $L$.

$$ R6 -= \frac{5}{6}R5, E_{65}^{-1} $$
$$ R5 -= \frac{4}{5}R4, E_{54}^{-1} $$
$$ R4 -= \frac{3}{4}R3, E_{43}^{-1} $$
$$ R3 -= \frac{2}{3}R2, E_{32}^{-1} $$
$$ R2 -= \frac{1}{2}R1, E_{21}^{-1} $$

The first row operation is $R6 = R6 - \frac{5}{6} \cdot R5$, which is $E_{65}^{-1}$.

Note that the order of the row operations has changed too: the row operations start from R6 and move up to R2, instead of from R2 down to R6.

Performing these row operations on an identity matrix results in $L$.

$$
L =
\begin{bmatrix}
           1 &            0 &            0 &            0 &            0 &           0 \\
-\frac{1}{2} &            1 &            0 &            0 &            0 &           0 \\
           0 & -\frac{2}{3} &            1 &            0 &            0 &           0 \\
           0 &            0 & -\frac{3}{4} &            1 &            0 &           0 \\
           0 &            0 &            0 & -\frac{4}{5} &            1 &           0 \\
           0 &            0 &            0 &            0 & -\frac{5}{6} &           1 \\
\end{bmatrix}
$$

We now have $K = LU$.

For the second part of the question, we must go back to $L^{-1}$ and find the formula for the matrix entries.

Before, we had stated

$$
E_{65}E_{54}E_{43}E_{32}E_{21}K = U
$$

Thus,
$$
L^{-1}K = U
$$

So

$$
L^{-1} = E_{65}E_{54}E_{43}E_{32}E_{21}
$$

We had performed these elimination matrices / row operations previously on $K$ to find $U$. We will do these on an identity matrix to find $L^{-1}$. The row operations and corresponding matrices are restated below.

$$ R2 += \frac{1}{2}R1, E_{21} $$
$$ R3 += \frac{2}{3}R2, E_{32} $$
$$ R4 += \frac{3}{4}R3, E_{43} $$
$$ R5 += \frac{4}{5}R4, E_{54} $$
$$ R6 += \frac{5}{6}R5, E_{65} $$

Performing these on an identity matrix yields

$$
L =
\begin{bmatrix}
          1 &           0 &           0 &           0 &           0 &           0 \\
\frac{1}{2} &           1 &           0 &           0 &           0 &           0 \\
\frac{1}{3} & \frac{2}{3} &           1 &           0 &           0 &           0 \\
\frac{1}{4} & \frac{1}{2} & \frac{3}{4} &           1 &           0 &           0 \\
\frac{1}{5} & \frac{2}{5} & \frac{3}{5} & \frac{4}{5} &           1 &           0 \\
\frac{1}{6} & \frac{1}{3} & \frac{1}{2} & \frac{2}{3} & \frac{5}{6} &           1 \\
\end{bmatrix}
$$

Looking at the pattern of the entries of $L$, you can see that if $i < j$, the entry is 0. If $i \geq j$, the entry is $\frac{j}{i}$.




#### Problem 26

This problem is more about observing patterns and properties about the Toeplitz matrix from Problem 25.

Following the problem's instructions on creating the matrix $7K^{-1}$ results in 

$$
7K^{-1} = 
\begin{bmatrix}
6 &  5 &  4 &  3 &  2 &  1 \\
5 & 10 &  8 &  6 &  4 &  2 \\
4 &  8 & 12 &  9 &  6 &  3 \\
3 &  6 &  9 & 12 &  8 &  4 \\
2 &  4 &  6 &  8 & 10 &  5 \\
1 &  2 &  3 &  4 &  5 &  6 \\
\end{bmatrix}

$$

The problem describes how $K^{-1}$ doesn't look great, but $7K^{-1}$ does, and that $K7K^{-1} = 7I$. This is shown in the Python code below.

In [8]:
import numpy as np

K = np.array([[ 2,-1, 0,  0,  0,  0],
              [-1, 2,-1,  0,  0,  0],
              [ 0,-1, 2, -1,  0,  0],
              [ 0, 0,-1,  2, -1,  0],
              [ 0, 0, 0, -1,  2, -1],
              [ 0, 0, 0,  0, -1,  2]])

K_inv = np.linalg.inv(K)
K_inv7 = 7*K_inv
Kx7xKinv = np.matmul(K,K_inv7)

print("K_inv = ")
print(K_inv)

print("7*K_inv = ")
print(K_inv7)

print("K*7*K_inv = ")
print(Kx7xKinv)

K_inv = 
[[0.85714286 0.71428571 0.57142857 0.42857143 0.28571429 0.14285714]
 [0.71428571 1.42857143 1.14285714 0.85714286 0.57142857 0.28571429]
 [0.57142857 1.14285714 1.71428571 1.28571429 0.85714286 0.42857143]
 [0.42857143 0.85714286 1.28571429 1.71428571 1.14285714 0.57142857]
 [0.28571429 0.57142857 0.85714286 1.14285714 1.42857143 0.71428571]
 [0.14285714 0.28571429 0.42857143 0.57142857 0.71428571 0.85714286]]
7*K_inv = 
[[ 6.  5.  4.  3.  2.  1.]
 [ 5. 10.  8.  6.  4.  2.]
 [ 4.  8. 12.  9.  6.  3.]
 [ 3.  6.  9. 12.  8.  4.]
 [ 2.  4.  6.  8. 10.  5.]
 [ 1.  2.  3.  4.  5.  6.]]
K*7*K_inv = 
[[ 7.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.77635684e-15  7.00000000e+00 -1.77635684e-15  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 4.44089210e-16  8.88178420e-16  7.00000000e+00 -1.77635684e-15
  -1.77635684e-15 -8.88178420e-16]
 [ 0.00000000e+00  0.00000000e+00  1.77635684e-15  7.00000000e+00
   1.77635684e-15  8